# @name createPoll

POST {{baseURL}}/polls
Content-Type: application/json
Authorization: Bearer {{$dotenv %developerAccessToken}}

{
  "title": "TTA: Pior membro do Servidor",
  "description": "A The TARDIS Awards começou, você está preparado? Vote abaixo para a categoria \"Pior membro do Servidor\"",
  "expireAt": "2024-04-26T12:00:00Z",
  "options": ["Far", "FarRed", "FarBlue", "Sergio", "Todas as opções acima"]
}
